import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'vi' | 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    'menu.overview': 'Tổng Quan',
    'menu.products': 'Sản Phẩm',
    'menu.orders': 'Đơn Hàng',
    'menu.partners': 'Khách Hàng',
    'menu.employees': 'Nhân Viên',
    'menu.supplierInvoices': 'Nhập Hàng',
    'menu.cashReceipts': 'Thu Tiền Mặt',
    'menu.transferReceipts': 'Thu Chuyển Khoản',
    'menu.currency': 'Tiền Tệ',
    'menu.priceList': 'Thiết Lập Giá',
    'menu.profile': 'Hồ Sơ',
    'menu.logout': 'Đăng Xuất',
    'transfer.title': 'Danh Sách Thu Tiền Chuyển Khoản',
    'transfer.searchPlaceholder': 'Tìm kiếm theo số phiếu thu...',
    'transfer.startDate': 'Từ Ngày',
    'transfer.endDate': 'Đến Ngày',
    'transfer.counterpartyPlaceholder': 'Tìm kiếm đối tác...',
    'transfer.operationType': 'Loại thu...',
    'transfer.bankAccount': 'Tài khoản ngân hàng...',
    'transfer.minAmount': 'Số tiền tối thiểu...',
    'transfer.maxAmount': 'Số tiền tối đa...',
    'transfer.currency': 'Loại tiền...',
    'transfer.purpose': 'Mục đích thu...',
    'transfer.sourceDocument': 'Chứng từ gốc...',
    'transfer.author': 'Người lập...',
    'transfer.search': 'Tìm kiếm',
    'transfer.searching': 'Đang tìm...',
    'transfer.loading': 'Đang tải...',
    'transfer.loadingMore': 'Đang tải thêm...',
    'transfer.noResults': 'Không tìm thấy phiếu thu',
    'transfer.authorLabel': 'Người lập',
    'overview.title': 'Báo Cáo Tổng Quan',
    'overview.startDate': 'Từ Ngày',
    'overview.endDate': 'Đến Ngày',
    'overview.confirm': 'Xác Nhận',
    'overview.revenue': 'Doanh Thu',
    'overview.orderQuantity': 'Số Lượng Đơn Hàng',
    'overview.cashCollection': 'Thu Tiền Mặt',
    'overview.transfer': 'Chuyển Khoản',
    'overview.debt': 'Công Nợ',
    'login.title': 'Chào Mừng Trở Lại',
    'login.subtitle': 'Vui lòng đăng nhập để tiếp tục',
    'login.username': 'Nhập tên đăng nhập . . .',
    'login.password': 'Nhập mật khẩu . . .',
    'login.button': 'Đăng Nhập',
    'login.signing': 'Đang đăng nhập...',
    'login.rememberMe': 'Ghi nhớ đăng nhập',
    'message.logoutSuccess': 'Đăng xuất thành công',
    'message.logoutFailed': 'Đăng xuất thất bại',
    'message.loginSuccess': 'Đăng nhập thành công',
    'message.loginFailed': 'Tên đăng nhập hoặc mật khẩu không đúng',
    'message.reportFailed': 'Không thể tải dữ liệu báo cáo',
    'message.productsFailed': 'Không thể tải danh sách sản phẩm',
    'products.title': 'Danh Sách Sản Phẩm',
    'products.searchPlaceholder': 'Tìm kiếm sản phẩm...',
    'products.allCategories': 'Tất cả danh mục',
    'products.categoryClothing': 'Quần áo',
    'products.categoryToys': 'Đồ chơi',
    'products.categoryAccessories': 'Phụ kiện',
    'products.search': 'Tìm kiếm',
    'products.searching': 'Đang tìm...',
    'products.loading': 'Đang tải...',
    'products.loadingMore': 'Đang tải thêm...',
    'products.noResults': 'Không tìm thấy sản phẩm',
    'products.newProduct': 'Thêm Sản Phẩm',
    'orders.title': 'Danh Sách Đơn Hàng',
    'orders.searchPlaceholder': 'Tìm kiếm theo mã đơn hàng...',
    'orders.partnerPlaceholder': 'Tìm kiếm khách hàng...',
    'orders.startDate': 'Từ Ngày',
    'orders.endDate': 'Đến Ngày',
    'orders.minPrice': 'Giá tối thiểu',
    'orders.maxPrice': 'Giá tối đa',
    'orders.allStatuses': 'Tất cả trạng thái',
    'orders.statusNew': 'Mới',
    'orders.statusProcessing': 'Đang xử lý',
    'orders.statusCompleted': 'Hoàn thành',
    'orders.statusCancelled': 'Đã hủy',
    'orders.search': 'Tìm kiếm',
    'orders.searching': 'Đang tìm...',
    'orders.loading': 'Đang tải...',
    'orders.loadingMore': 'Đang tải thêm...',
    'orders.noResults': 'Không tìm thấy đơn hàng',
    'orders.items': 'sản phẩm',
    'orders.addNew': 'Thêm mới',
    'message.ordersFailed': 'Không thể tải danh sách đơn hàng',
    'partners.title': 'Danh Sách Đối Tác',
    'partners.searchPlaceholder': 'Tìm kiếm theo mã, tên...',
    'partners.allTypes': 'Tất cả loại',
    'partners.allGenders': 'Tất cả giới tính',
    'partners.active': 'Đang hoạt động',
    'partners.inactive': 'Ngừng hoạt động',
    'partners.partner': 'Khách hàng',
    'partners.supplier': 'Nhà cung cấp',
    'partners.search': 'Tìm kiếm',
    'partners.searching': 'Đang tìm...',
    'partners.loading': 'Đang tải...',
    'partners.loadingMore': 'Đang tải thêm...',
    'partners.noResults': 'Không tìm thấy đối tác',
    'partners.phone': 'Điện thoại',
    'partners.email': 'Email',
    'partners.address': 'Địa chỉ',
    'partners.notes': 'Ghi chú',
    'message.partnersFailed': 'Không thể tải danh sách đối tác',
    'supplierInvoices.title': 'Danh Sách Đơn Nhập Hàng',
    'supplierInvoices.searchPlaceholder': 'Tìm kiếm theo mã đơn nhập...',
    'supplierInvoices.startDate': 'Từ Ngày',
    'supplierInvoices.endDate': 'Đến Ngày',
    'supplierInvoices.authorPlaceholder': 'Tìm kiếm người lập...',
    'supplierInvoices.companyPlaceholder': 'Tìm kiếm công ty...',
    'supplierInvoices.counterpartyPlaceholder': 'Tìm kiếm đối tác...',
    'supplierInvoices.operationType': 'Loại nghiệp vụ...',
    'supplierInvoices.search': 'Tìm kiếm',
    'supplierInvoices.searching': 'Đang tìm...',
    'supplierInvoices.loading': 'Đang tải...',
    'supplierInvoices.loadingMore': 'Đang tải thêm...',
    'supplierInvoices.noResults': 'Không tìm thấy đơn nhập hàng',
    'supplierInvoices.status.posted': 'Đã ghi sổ',
    'supplierInvoices.status.draft': 'Nháp',
    'supplierInvoices.author': 'Người lập',
    'supplierInvoices.contract': 'Hợp đồng',
    'supplierInvoices.counterparty': 'Đối tác',
    'supplierInvoices.responsible': 'Người phụ trách',
    'supplierInvoices.vat': 'Thuế GTGT',
    'supplierInvoices.unit': 'Đơn vị',
    'supplierInvoices.order': 'Đơn đặt hàng',
    'supplierInvoices.failed': 'Không thể tải danh sách đơn nhập hàng',
    'product.detail.title': 'Chi Tiết Sản Phẩm',
    'product.detail.code': 'Mã Sản Phẩm',
    'product.detail.name': 'Tên Sản Phẩm',
    'product.detail.category': 'Danh Mục',
    'product.detail.price': 'Giá',
    'product.detail.baseUnit': 'Đơn Vị Cơ Bản',
    'product.detail.riCoefficient': 'Hệ Số Ri',
    'product.detail.description': 'Mô Tả',
    'product.detail.notes': 'Ghi Chú',
    'product.detail.edit': 'Chỉnh Sửa',
    'product.detail.delete': 'Xóa',
    'product.detail.back': 'Quay Lại',
    'product.detail.downloadImage': 'Tải Ảnh',
    'product.detail.noImage': 'Không có ảnh',
    'product.detail.notFound': 'Không Tìm Thấy Sản Phẩm',
    'product.detail.loadError': 'Không thể tải thông tin sản phẩm',
    'product.detail.loading': 'Đang tải...',
    "transferReceiptDetail": {
      "title": "Chi tiết phiếu thu",
      "idMissing": "ID phiếu thu không tồn tại",
      "fetchError": "Không thể tải thông tin phiếu thu",
      "notFound": "Không tìm thấy phiếu thu",
      "backToList": "Quay lại danh sách",
      "deleteNotImplemented": "Chức năng xóa chưa được triển khai",
      "date": "Ngày thu",
      "customer": "Khách hàng",
      "amount": "Số tiền",
      "bankAccount": "Tài khoản ngân hàng",
      "order": "Đơn hàng",
      "collector": "Người thu",
      "unknown": "Chưa xác định",
      "notes": "Ghi chú"
      }
  },
  en: {
    'menu.overview': 'Overview',
    'menu.products': 'Products',
    'menu.orders': 'Orders',
    'menu.partners': 'Partners',
    'menu.employees': 'Employees',
    'menu.supplierInvoices': 'Supplier Invoices',
    'menu.cashReceipts': 'Cash Receipts',
    'menu.transferReceipts': 'Transfer Receipts',
    'menu.currency': 'Currency',
    'menu.priceList': 'Set Price List',
    'menu.profile': 'Profile',
    'menu.logout': 'Logout',
    'transfer.title': 'Transfer Collection List',
    'transfer.searchPlaceholder': 'Search by transfer number...',
    'transfer.startDate': 'Start Date',
    'transfer.endDate': 'End Date',
    'transfer.counterpartyPlaceholder': 'Search counterparty...',
    'transfer.operationType': 'Operation type...',
    'transfer.bankAccount': 'Bank account...',
    'transfer.minAmount': 'Minimum amount...',
    'transfer.maxAmount': 'Maximum amount...',
    'transfer.currency': 'Currency...',
    'transfer.purpose': 'Purpose...',
    'transfer.sourceDocument': 'Source document...',
    'transfer.author': 'Author...',
    'transfer.search': 'Search',
    'transfer.searching': 'Searching...',
    'transfer.loading': 'Loading...',
    'transfer.loadingMore': 'Loading more...',
    'transfer.noResults': 'No transfers found',
    'transfer.authorLabel': 'Author',
    'overview.title': 'Overview Report',
    'overview.startDate': 'Start Date',
    'overview.endDate': 'End Date',
    'overview.confirm': 'Confirm',
    'overview.revenue': 'Revenue',
    'overview.orderQuantity': 'Order Quantity',
    'overview.cashCollection': 'Cash Collection',
    'overview.transfer': 'Transfer',
    'overview.debt': 'Debt',
    'login.title': 'Welcome Back',
    'login.subtitle': 'Please sign in to continue',
    'login.username': 'Enter username . . .',
    'login.password': 'Enter password . . .',
    'login.button': 'Login',
    'login.signing': 'Signing in...',
    'login.rememberMe': 'Remember to log in',
    'message.logoutSuccess': 'Logout successful',
    'message.logoutFailed': 'Logout failed',
    'message.loginSuccess': 'Login successful',
    'message.loginFailed': 'Incorrect username or password',
    'message.reportFailed': 'Failed to fetch report data',
    'message.productsFailed': 'Failed to load products',
    'products.title': 'Product List',
    'products.searchPlaceholder': 'Search products...',
    'products.allCategories': 'All categories',
    'products.categoryClothing': 'Clothing',
    'products.categoryToys': 'Toys',
    'products.categoryAccessories': 'Accessories',
    'products.search': 'Search',
    'products.searching': 'Searching...',
    'products.loading': 'Loading...',
    'products.loadingMore': 'Loading more...',
    'products.noResults': 'No products found',
    'products.newProduct': 'New Product',
    'orders.title': 'Order List',
    'orders.searchPlaceholder': 'Search by order number...',
    'orders.partnerPlaceholder': 'Search partner...',
    'orders.startDate': 'Start Date',
    'orders.endDate': 'End Date',
    'orders.minPrice': 'Min price',
    'orders.maxPrice': 'Max price',
    'orders.allStatuses': 'All statuses',
    'orders.statusNew': 'New',
    'orders.statusProcessing': 'Processing',
    'orders.statusCompleted': 'Completed',
    'orders.statusCancelled': 'Cancelled',
    'orders.search': 'Search',
    'orders.searching': 'Searching...',
    'orders.loading': 'Loading...',
    'orders.loadingMore': 'Loading more...',
    'orders.noResults': 'No orders found',
    'orders.items': 'items',
    'orders.addNew': 'Add New',
    'message.ordersFailed': 'Failed to load orders',
    'partners.title': 'Partner List',
    'partners.searchPlaceholder': 'Search by code, name...',
    'partners.allTypes': 'All types',
    'partners.allGenders': 'All genders',
    'partners.active': 'Active',
    'partners.inactive': 'Inactive',
    'partners.partner': 'partner',
    'partners.supplier': 'Supplier',
    'partners.search': 'Search',
    'partners.searching': 'Searching...',
    'partners.loading': 'Loading...',
    'partners.loadingMore': 'Loading more...',
    'partners.noResults': 'No partners found',
    'partners.phone': 'Phone',
    'partners.email': 'Email',
    'partners.address': 'Address',
    'partners.notes': 'Notes',
    'message.partnersFailed': 'Failed to load partners',
    'supplierInvoices.title': 'List of supplierInvoicesed Orders',
    'supplierInvoices.searchPlaceholder': 'Search by invoice ID...',
    'supplierInvoices.startDate': 'Start Date',
    'supplierInvoices.endDate': 'End Date',
    'supplierInvoices.authorPlaceholder': 'Search by author...',
    'supplierInvoices.companyPlaceholder': 'Search by company...',
    'supplierInvoices.counterpartyPlaceholder': 'Search by counterparty...',
    'supplierInvoices.operationType': 'Operation type...',
    'supplierInvoices.search': 'Search',
    'supplierInvoices.searching': 'Searching...',
    'supplierInvoices.loading': 'Loading...',
    'supplierInvoices.loadingMore': 'Loading more...',
    'supplierInvoices.noResults': 'No invoices found',
    'supplierInvoices.status.posted': 'Posted',
    'supplierInvoices.status.draft': 'Draft',
    'supplierInvoices.author': 'Author',
    'supplierInvoices.contract': 'Contract',
    'supplierInvoices.counterparty': 'Counterparty',
    'supplierInvoices.responsible': 'Responsible',
    'supplierInvoices.vat': 'VAT',
    'supplierInvoices.unit': 'Unit',
    'supplierInvoices.order': 'Order',
    'supplierInvoices.failed': 'Failed to load supplier invoices',
    'product.detail.title': 'Product Details',
    'product.detail.code': 'Product Code',
    'product.detail.name': 'Product Name',
    'product.detail.category': 'Category',
    'product.detail.price': 'Price',
    'product.detail.baseUnit': 'Base Unit',
    'product.detail.riCoefficient': 'Ri Coefficient',
    'product.detail.description': 'Description',
    'product.detail.notes': 'Notes',
    'product.detail.edit': 'Edit',
    'product.detail.delete': 'Delete',
    'product.detail.back': 'Back',
    'product.detail.downloadImage': 'Download Image',
    'product.detail.noImage': 'No image available',
    'product.detail.notFound': 'Product Not Found',
    'product.detail.loadError': 'Failed to load product details',
    'product.detail.loading': 'Loading...',
    "transferReceiptDetail": {
      "title": "Receipt Details",
      "idMissing": "Receipt ID is missing",
      "fetchError": "Unable to load receipt information",
      "notFound": "Receipt not found",
      "backToList": "Back to list",
      "deleteNotImplemented": "Delete function is not yet implemented",
      "date": "Date",
      "customer": "Customer",
      "amount": "Amount",
      "bankAccount": "Bank Account",
      "order": "Order",
      "collector": "Collector",
      "unknown": "Unknown",
      "notes": "Notes"
    }
  },
  zh: {
    'menu.overview': '总览',
    'menu.products': '产品',
    'menu.orders': '订单',
    'menu.partners': '客户',
    'menu.employees': '员工',
    'menu.supplierInvoices': '进口商品',
    'menu.cashReceipts': '现金收款',
    'menu.transferReceipts': '转账收款',
    'menu.currency': '货币',
    'menu.priceList': '设置价格表',
    'menu.profile': '个人资料',
    'menu.logout': '退出登录',
    'transfer.title': '转账收款列表',
    'transfer.searchPlaceholder': '按转账号码搜索...',
    'transfer.startDate': '开始日期',
    'transfer.endDate': '结束日期',
    'transfer.counterpartyPlaceholder': '搜索交易对手...',
    'transfer.operationType': '操作类型...',
    'transfer.bankAccount': '银行账户...',
    'transfer.minAmount': '最小金额...',
    'transfer.maxAmount': '最大金额...',
    'transfer.currency': '货币...',
    'transfer.purpose': '用途...',
    'transfer.sourceDocument': '源文件...',
    'transfer.author': '作者...',
    'transfer.search': '搜索',
    'transfer.searching': '搜索中...',
    'transfer.loading': '加载中...',
    'transfer.loadingMore': '加载更多...',
    'transfer.noResults': '未找到转账',
    'transfer.authorLabel': '作者',
    'overview.title': '概览报告',
    'overview.startDate': '开始日期',
    'overview.endDate': '结束日期',
    'overview.confirm': '确认',
    'overview.revenue': '收入',
    'overview.orderQuantity': '订单数量',
    'overview.cashCollection': '现金收款',
    'overview.transfer': '转账',
    'overview.debt': '债务',
    'login.title': '欢迎回来',
    'login.subtitle': '请登录以继续',
    'login.username': '输入用户名 . . .',
    'login.password': '输入密码 . . .',
    'login.button': '登录',
    'login.signing': '正在登录...',
    'login.rememberMe': '记得登录',
    'message.logoutSuccess': '退出登录成功',
    'message.logoutFailed': '退出登录失败',
    'message.loginSuccess': '登录成功',
    'message.loginFailed': '用户名或密码错误',
    'message.reportFailed': '无法获取报告数据',
    'message.productsFailed': '无法加载产品列表',
    'products.title': '产品列表',
    'products.searchPlaceholder': '搜索产品...',
    'products.allCategories': '所有类别',
    'products.categoryClothing': '服装',
    'products.categoryToys': '玩具',
    'products.categoryAccessories': '配件',
    'products.search': '搜索',
    'products.searching': '搜索中...',
    'products.loading': '加载中...',
    'products.loadingMore': '加载更多...',
    'products.noResults': '未找到产品',
    'products.newProduct': '新产品',
    'orders.title': '订单列表',
    'orders.searchPlaceholder': '按订单号搜索...',
    'orders.partnerPlaceholder': '搜索客户...',
    'orders.startDate': '开始日期',
    'orders.endDate': '结束日期',
    'orders.minPrice': '最低价格',
    'orders.maxPrice': '最高价格',
    'orders.allStatuses': '所有状态',
    'orders.statusNew': '新订单',
    'orders.statusProcessing': '处理中',
    'orders.statusCompleted': '已完成',
    'orders.statusCancelled': '已取消',
    'orders.search': '搜索',
    'orders.searching': '搜索中...',
    'orders.loading': '加载中...',
    'orders.loadingMore': '加载更多...',
    'orders.noResults': '未找到订单',
    'orders.items': '件商品',
    'orders.addNew': '新增',
    'message.ordersFailed': '无法加载订单列表',
    'partners.title': '合作伙伴列表',
    'partners.searchPlaceholder': '按代码、名称搜索...',
    'partners.allTypes': '所有类型',
    'partners.allGenders': '所有性别',
    'partners.active': '活跃',
    'partners.inactive': '不活跃',
    'partners.partner': '客户',
    'partners.supplier': '供应商',
    'partners.search': '搜索',
    'partners.searching': '搜索中...',
    'partners.loading': '加载中...',
    'partners.loadingMore': '加载更多...',
    'partners.noResults': '未找到合作伙伴',
    'partners.phone': '电话',
    'partners.email': '电子邮件',
    'partners.address': '地址',
    'partners.notes': '备注',
    'message.partnersFailed': '无法加载合作伙伴列表',
    'supplierInvoices.title': '进货单列表',
    'supplierInvoices.searchPlaceholder': '按发票ID搜索...',
    'supplierInvoices.startDate': '开始日期',
    'supplierInvoices.endDate': '结束日期',
    'supplierInvoices.authorPlaceholder': '按作者搜索...',
    'supplierInvoices.companyPlaceholder': '按公司搜索...',
    'supplierInvoices.counterpartyPlaceholder': '按交易对手搜索...',
    'supplierInvoices.operationType': '操作类型...',
    'supplierInvoices.search': '搜索',
    'supplierInvoices.searching': '搜索中...',
    'supplierInvoices.loading': '加载中...',
    'supplierInvoices.loadingMore': '加载更多...',
    'supplierInvoices.noResults': '未找到发票',
    'supplierInvoices.status.posted': '已过账',
    'supplierInvoices.status.draft': '草稿',
    'supplierInvoices.author': '作者',
    'supplierInvoices.contract': '合同',
    'supplierInvoices.counterparty': '交易对手',
    'supplierInvoices.responsible': '负责人',
    'supplierInvoices.vat': '增值税',
    'supplierInvoices.unit': '单位',
    'supplierInvoices.order': '订单',
    'supplierInvoices.failed': '无法加载供应商发票',
    'product.detail.title': '产品详情',
    'product.detail.code': '产品代码',
    'product.detail.name': '产品名称',
    'product.detail.category': '类别',
    'product.detail.price': '价格',
    'product.detail.baseUnit': '基本单位',
    'product.detail.riCoefficient': 'Ri系数',
    'product.detail.description': '描述',
    'product.detail.notes': '备注',
    'product.detail.edit': '编辑',
    'product.detail.delete': '删除',
    'product.detail.back': '返回',
    'product.detail.downloadImage': '下载图片',
    'product.detail.noImage': '无图片',
    'product.detail.notFound': '未找到产品',
    'product.detail.loadError': '无法加载产品详情',
    'product.detail.loading': '加载中...',
    "transferReceiptDetail": {
      "title": "收据详情",
      "idMissing": "收据ID不存在",
      "fetchError": "无法加载收据信息",
      "notFound": "未找到收据",
      "backToList": "返回列表",
      "deleteNotImplemented": "删除功能尚未实现",
      "date": "日期",
      "customer": "客户",
      "amount": "金额",
      "bankAccount": "银行账户",
      "order": "订单",
      "collector": "收款人",
      "unknown": "未知",
      "notes": "备注"
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('vi');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['vi']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}